name: apply-pulumi
on:
  push:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - run: pulumi version
      - run: npm ci
      - run: npm run test
  preview:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: dev
