name: preview-pulumi
on:
  pull_request:
    branches: ["main"]
jobs:
  unit-tests:
    uses: ./.github/workflows/test.yml
  preview-base-dev:
    needs: unit-tests
    uses: ./.github/workflows/pulumi-cmd.yml
    with:
      command: preview
      stack-name: dev
      work-dir: ./base
    secrets:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  preview-app-dev:
    needs: preview-base-dev
    uses: ./.github/workflows/pulumi-cmd.yml
    with:
      command: preview
      stack-name: dev
      work-dir: ./base
    secrets:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
